name: daily-meme-alert-cron
on:
  schedule:
    - cron: '30 6 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://memecraft.vercel.app/api/dailyMemeAlert' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
